- name: Enable Firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Remove Cockpit Service from Firewalld
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    state: disabled
  notify:
    - Restart Firewalld

- name: Remove dhcpv6-client Service from Firewalld
  ansible.posix.firewalld:
    service: dhcpv6-client
    permanent: true
    state: disabled
  notify:
    - Restart Firewalld
