timezone: America/Chicago
dns:
  searchdomains:
    - test.lan
  nameservers:
    - 1.1.1.1
    - 9.9.9.9
  hosts:
    - ip: 192.168.1.20
      names:
        - test
        - test.local
    - ip: 192.168.1.21
      names:
        - test1
        - test1.local 
users:
  - name: user
  - name: user2
    comment: "A user who just NEEDS to be cool and use ZSH"
    shell: /bin/zsh
  - name: admin
    password: $6$UkAmkRMIknoOijJ8$o9f7KjoDXW0/yvwVf2rzshiPe7f0uBY99Ve9tn2uyIt1/U5RyV67k37tJY72TfBxzYCgk2vXWNo439jAgMyS41
    comment: "Admin User"
    shell: /bin/zsh
    groups: wheel
